schema_version = "1.0.0"
id = "DarkPurpleTheme"
version = "1.0.1"
name = "Dark Purple Theme"
tagline = "Dark theme with purple accent"
maintainer = "Salman <salmanfaris5397@gmail.com>"
type = "theme"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-2.0-or-later",
]